spring:
datasource:
  url: jdbc:mysql://ustinterview.cs3a8uy2ctvi.ap-south-1.rds.amazonaws.com:3306/ustinterviews
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: Awscloud#098
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 5000

